package us.joonas;

import com.vaadin.flow.component.html.Anchor;

import com.vaadin.flow.component.orderedlayout.VerticalLayout;

import com.vaadin.flow.component.orderedlayout.HorizontalLayout;

import com.vaadin.flow.theme.lumo.LumoUtility;

import com.vaadin.flow.component.html.H2;

import com.vaadin.flow.component.html.Span;

import com.vaadin.flow.component.combobox.ComboBox;

import com.vaadin.flow.component.datepicker.DatePicker;

import com.vaadin.flow.component.textfield.TextField;

import com.vaadin.flow.component.html.Div;

import com.vaadin.flow.component.button.Button;

import com.vaadin.flow.component.icon.Icon;

import com.vaadin.flow.component.html.H3;

import com.vaadin.flow.component.html.H1;
import com.vaadin.flow.component.html.Main;
import jakarta.annotation.security.PermitAll;
import com.vaadin.flow.router.PageTitle;
import com.vaadin.flow.router.Route;
import com.vaadin.flow.router.Menu;

@PageTitle("Figma Hotels")
@PermitAll
@Route(value = "figma-hotels")
@Menu(title = "Figma Hotels", icon = "vaadin:building")
public class FigmaHotels extends Main {

    public FigmaHotels() {

        VerticalLayout verticallayout = new VerticalLayout();
        verticallayout.getStyle().set("height", "100%").set("backgroundColor", "#ffffff");
        HorizontalLayout horizontallayout = new HorizontalLayout();
        horizontallayout.getStyle().set("backgroundColor", "#f5f8fd");
        horizontallayout.addClassNames(LumoUtility.AlignSelf.STRETCH, LumoUtility.Gap.SMALL, LumoUtility.Padding.MEDIUM, LumoUtility.AlignItems.CENTER);
        horizontallayout.getElement().getThemeList().add("spacing");
        VerticalLayout verticallayout2 = new VerticalLayout();
        verticallayout2.addClassNames(LumoUtility.Flex.GROW, LumoUtility.Gap.SMALL);
        verticallayout2.getElement().getThemeList().add("spacing");
        H2 hotels = new H2("Hotels");
        hotels.addClassNames(LumoUtility.AlignSelf.STRETCH);
        verticallayout2.add(hotels);
        Anchor frontpage = new Anchor();
        frontpage.setHref("https://www.figma.com/design/vFW7IaECFMPUzn7pPAjMKM/Vaadin-Copilot---Figma-to-Copilot-test?node-id=903-14924&t=omrG7zATiPnBzgVd-0");
        frontpage.setText("Source Figma design");
        Span exploreAndOverseeGue = new Span("Explore and oversee guest details, such as contact information and booking records.");
        exploreAndOverseeGue.addClassNames(LumoUtility.AlignSelf.STRETCH);
        verticallayout2.add(frontpage);
        verticallayout2.add(exploreAndOverseeGue);
        horizontallayout.add(verticallayout2);
        verticallayout.add(horizontallayout);
        VerticalLayout verticallayout3 = new VerticalLayout();
        verticallayout3.addClassNames(LumoUtility.AlignSelf.STRETCH, LumoUtility.Height.FULL, LumoUtility.Gap.LARGE, LumoUtility.Padding.MEDIUM);
        verticallayout3.getElement().getThemeList().add("spacing");
        HorizontalLayout horizontallayout2 = new HorizontalLayout();
        horizontallayout2.addClassNames(LumoUtility.AlignSelf.STRETCH, LumoUtility.Gap.MEDIUM, LumoUtility.AlignItems.END);
        horizontallayout2.getElement().getThemeList().add("spacing");
        ComboBox location = new ComboBox("Location");
        horizontallayout2.add(location);
        HorizontalLayout horizontallayout3 = new HorizontalLayout();
        horizontallayout3.addClassNames(LumoUtility.Gap.XSMALL, LumoUtility.AlignItems.END);
        horizontallayout3.getElement().getThemeList().add("spacing");
        DatePicker dates = new DatePicker("Dates");
        horizontallayout3.add(dates);
        DatePicker label = new DatePicker("Label");
        horizontallayout3.add(label);
        horizontallayout2.add(horizontallayout3);
        HorizontalLayout horizontallayout4 = new HorizontalLayout();
        horizontallayout4.addClassNames(LumoUtility.Gap.XSMALL, LumoUtility.AlignItems.END);
        horizontallayout4.getElement().getThemeList().add("spacing");
        TextField priceRange = new TextField("Price range");
        Div div = new Div();
        Span a = new Span("€");
        div.add(a);
        priceRange.setSuffixComponent(div);
        horizontallayout4.add(priceRange);
        TextField label2 = new TextField("Label");
        Div div2 = new Div();
        Span a2 = new Span("€");
        div2.add(a2);
        label2.setSuffixComponent(div2);
        horizontallayout4.add(label2);
        horizontallayout2.add(horizontallayout4);
        HorizontalLayout horizontallayout5 = new HorizontalLayout();
        horizontallayout5.addClassNames(LumoUtility.Flex.GROW, LumoUtility.Gap.XSMALL, LumoUtility.JustifyContent.END, LumoUtility.AlignItems.CENTER);
        horizontallayout5.getElement().getThemeList().add("spacing");
        Button button = new Button();
        button.setThemeName("icon");
        Icon icon = new Icon("lumo:unordered-list");
        icon.getStyle().set("padding", "var(--lumo-space-xs)");
        button.setPrefixComponent(icon);
        horizontallayout5.add(button);
        Button button2 = new Button();
        button2.setThemeName("icon");
        Icon icon2 = new Icon("vaadin:map-marker");
        icon2.getStyle().set("padding", "var(--lumo-space-xs)");
        button2.setPrefixComponent(icon2);
        horizontallayout5.add(button2);
        horizontallayout2.add(horizontallayout5);
        verticallayout3.add(horizontallayout2);
        VerticalLayout verticallayout4 = new VerticalLayout();
        verticallayout4.addClassNames(LumoUtility.AlignSelf.STRETCH, LumoUtility.Height.FULL, LumoUtility.Gap.MEDIUM);
        verticallayout4.getElement().getThemeList().add("spacing");
        Div div3 = new Div();
        div3.addClassNames(LumoUtility.AlignSelf.STRETCH);
        Div div4 = new Div();
        div4.getStyle().set("backgroundColor", "#d9d9d9").set("width", "160px").set("height", "146px");
        div4.addClassNames(LumoUtility.Height.FULL, LumoUtility.BorderRadius.SMALL);
Div div30 = new Div();
div30.getStyle().set("backgroundColor", "#d9d9d9").set("width", "160px").set("height", "146px");
div30.addClassNames(LumoUtility.BorderRadius.SMALL);
div4.add(div30);
        div3.add(div4);
        VerticalLayout verticallayout5 = new VerticalLayout();
        verticallayout5.addClassNames(LumoUtility.Flex.GROW, LumoUtility.Gap.MEDIUM, LumoUtility.Padding.MEDIUM);
        verticallayout5.getElement().getThemeList().add("spacing");
        VerticalLayout verticallayout6 = new VerticalLayout();
        verticallayout6.addClassNames(LumoUtility.AlignSelf.STRETCH, LumoUtility.Gap.SMALL);
        verticallayout6.getElement().getThemeList().add("spacing");
        HorizontalLayout horizontallayout6 = new HorizontalLayout();
        horizontallayout6.addClassNames(LumoUtility.Gap.MEDIUM, LumoUtility.AlignItems.CENTER);
        horizontallayout6.getElement().getThemeList().add("spacing");
        H3 urbanOasisHotel = new H3("Urban Oasis Hotel");
        horizontallayout6.add(urbanOasisHotel);
        Span hotPrice = new Span("Hot price");
        hotPrice.getElement().getThemeList().add("badge pill");
        horizontallayout6.add(hotPrice);
        verticallayout6.add(horizontallayout6);
        HorizontalLayout horizontallayout7 = new HorizontalLayout();
        horizontallayout7.addClassNames(LumoUtility.AlignSelf.STRETCH, LumoUtility.Gap.LARGE, LumoUtility.AlignItems.CENTER);
        horizontallayout7.getElement().getThemeList().add("spacing");
        HorizontalLayout horizontallayout8 = new HorizontalLayout();
        horizontallayout8.addClassNames(LumoUtility.Gap.XSMALL, LumoUtility.AlignItems.CENTER);
        horizontallayout8.getElement().getThemeList().add("spacing");
        HorizontalLayout horizontallayout9 = new HorizontalLayout();
        horizontallayout9.setClassName("gap-x-s");
        Div div5 = new Div();
        div5.getStyle().set("backgroundColor", "#d9d9d9").set("width", "20px").set("height", "20px");
        div5.addClassNames(LumoUtility.BorderRadius.SMALL);
        horizontallayout9.add(div5);
        Div div6 = new Div();
        horizontallayout9.add(div6);
        horizontallayout8.add(horizontallayout9);
        Span kamppiHelsinki = new Span("Kamppi, Helsinki");
        kamppiHelsinki.addClassNames(LumoUtility.FontSize.XSMALL);
        horizontallayout8.add(kamppiHelsinki);
        horizontallayout7.add(horizontallayout8);
        HorizontalLayout horizontallayout10 = new HorizontalLayout();
        horizontallayout10.addClassNames(LumoUtility.Gap.SMALL, LumoUtility.AlignItems.CENTER);
        horizontallayout10.getElement().getThemeList().add("spacing");
        HorizontalLayout horizontallayout11 = new HorizontalLayout();
        horizontallayout11.setClassName("gap-x-m");
        Div div7 = new Div();
        div7.getStyle().set("backgroundColor", "#d9d9d9").set("width", "20px").set("height", "20px");
        div7.addClassNames(LumoUtility.BorderRadius.SMALL);
        horizontallayout11.add(div7);
        Div div8 = new Div();
        horizontallayout11.add(div8);
        horizontallayout10.add(horizontallayout11);
        Span a89 = new Span("8.9");
        a89.addClassNames(LumoUtility.FontSize.XSMALL);
        horizontallayout10.add(a89);
        horizontallayout7.add(horizontallayout10);
        verticallayout6.add(horizontallayout7);
        verticallayout5.add(verticallayout6);
        HorizontalLayout horizontallayout12 = new HorizontalLayout();
        horizontallayout12.addClassNames(LumoUtility.AlignSelf.STRETCH, LumoUtility.Gap.SMALL, LumoUtility.AlignItems.CENTER);
        horizontallayout12.getElement().getThemeList().add("spacing");
        Span Beds = new Span("2 beds");
        horizontallayout12.add(Beds);
        Span a3 = new Span("•");
        a3.setClassName("text-xxs");
        horizontallayout12.add(a3);
        Span M = new Span("24 m²");
        horizontallayout12.add(M);
        Span a4 = new Span("•");
        a4.setClassName("text-xxs");
        horizontallayout12.add(a4);
        Span Guests = new Span("3 guests");
        horizontallayout12.add(Guests);
        verticallayout5.add(horizontallayout12);
        div3.add(verticallayout5);
        VerticalLayout verticallayout7 = new VerticalLayout();
        verticallayout7.addClassNames(LumoUtility.Height.FULL, LumoUtility.Gap.XSMALL, LumoUtility.JustifyContent.CENTER, LumoUtility.AlignItems.END);
        verticallayout7.getElement().getThemeList().add("spacing");
        H2 a182 = new H2("182€");
        verticallayout7.add(a182);
        Span night = new Span("/ night");
        night.addClassNames(LumoUtility.FontSize.SMALL);
        verticallayout7.add(night);
        div3.add(verticallayout7);
        verticallayout4.add(div3);
        Div div9 = new Div();
        div9.getStyle().set("width", "908px").set("height", "1px");
        div9.addClassNames(LumoUtility.AlignSelf.STRETCH, LumoUtility.Background.CONTRAST_20, LumoUtility.BorderRadius.SMALL);
        verticallayout4.add(div9);
        Div div10 = new Div();
        div10.addClassNames(LumoUtility.AlignSelf.STRETCH);
        Div div11 = new Div();
        div11.getStyle().set("backgroundColor", "#d9d9d9").set("width", "160px").set("height", "146px");
        div11.addClassNames(LumoUtility.Height.FULL, LumoUtility.BorderRadius.SMALL);
        div10.add(div11);
        VerticalLayout verticallayout8 = new VerticalLayout();
        verticallayout8.addClassNames(LumoUtility.Flex.GROW, LumoUtility.Gap.MEDIUM, LumoUtility.Padding.MEDIUM);
        verticallayout8.getElement().getThemeList().add("spacing");
        VerticalLayout verticallayout9 = new VerticalLayout();
        verticallayout9.addClassNames(LumoUtility.AlignSelf.STRETCH, LumoUtility.Gap.SMALL);
        verticallayout9.getElement().getThemeList().add("spacing");
        HorizontalLayout horizontallayout13 = new HorizontalLayout();
        horizontallayout13.addClassNames(LumoUtility.Gap.MEDIUM, LumoUtility.AlignItems.CENTER);
        horizontallayout13.getElement().getThemeList().add("spacing");
        H3 eleganceRetreat = new H3("Elegance Retreat");
        horizontallayout13.add(eleganceRetreat);
        Span popular = new Span("Popular");
        popular.getElement().getThemeList().add("badge pill");
        horizontallayout13.add(popular);
        verticallayout9.add(horizontallayout13);
        HorizontalLayout horizontallayout14 = new HorizontalLayout();
        horizontallayout14.addClassNames(LumoUtility.AlignSelf.STRETCH, LumoUtility.Gap.LARGE, LumoUtility.AlignItems.CENTER);
        horizontallayout14.getElement().getThemeList().add("spacing");
        HorizontalLayout horizontallayout15 = new HorizontalLayout();
        horizontallayout15.addClassNames(LumoUtility.Gap.XSMALL, LumoUtility.AlignItems.CENTER);
        horizontallayout15.getElement().getThemeList().add("spacing");
        HorizontalLayout horizontallayout16 = new HorizontalLayout();
        horizontallayout16.setClassName("gap-x-s");
        Div div12 = new Div();
        div12.getStyle().set("backgroundColor", "#d9d9d9").set("width", "20px").set("height", "20px");
        div12.addClassNames(LumoUtility.BorderRadius.SMALL);
        horizontallayout16.add(div12);
        Div div13 = new Div();
        horizontallayout16.add(div13);
        horizontallayout15.add(horizontallayout16);
        Span kluuviHelsinki = new Span("Kluuvi, Helsinki");
        kluuviHelsinki.addClassNames(LumoUtility.FontSize.XSMALL);
        horizontallayout15.add(kluuviHelsinki);
        horizontallayout14.add(horizontallayout15);
        HorizontalLayout horizontallayout17 = new HorizontalLayout();
        horizontallayout17.addClassNames(LumoUtility.Gap.SMALL, LumoUtility.AlignItems.CENTER);
        horizontallayout17.getElement().getThemeList().add("spacing");
        HorizontalLayout horizontallayout18 = new HorizontalLayout();
        horizontallayout18.setClassName("gap-x-m");
        Div div14 = new Div();
        div14.getStyle().set("backgroundColor", "#d9d9d9").set("width", "20px").set("height", "20px");
        div14.addClassNames(LumoUtility.BorderRadius.SMALL);
        horizontallayout18.add(div14);
        Div div15 = new Div();
        horizontallayout18.add(div15);
        horizontallayout17.add(horizontallayout18);
        Span a92 = new Span("9.2");
        a92.addClassNames(LumoUtility.FontSize.XSMALL);
        horizontallayout17.add(a92);
        horizontallayout14.add(horizontallayout17);
        verticallayout9.add(horizontallayout14);
        verticallayout8.add(verticallayout9);
        HorizontalLayout horizontallayout19 = new HorizontalLayout();
        horizontallayout19.addClassNames(LumoUtility.AlignSelf.STRETCH, LumoUtility.Gap.SMALL, LumoUtility.AlignItems.CENTER);
        horizontallayout19.getElement().getThemeList().add("spacing");
        Span KingBed1QueenBed = new Span("1 king bed, 1 queen bed");
        horizontallayout19.add(KingBed1QueenBed);
        Span a5 = new Span("•");
        a5.setClassName("text-xxs");
        horizontallayout19.add(a5);
        Span M2 = new Span("30 m²");
        horizontallayout19.add(M2);
        Span a6 = new Span("•");
        a6.setClassName("text-xxs");
        horizontallayout19.add(a6);
        Span Adults1Child = new Span("2 adults, 1 child");
        horizontallayout19.add(Adults1Child);
        verticallayout8.add(horizontallayout19);
        div10.add(verticallayout8);
        VerticalLayout verticallayout10 = new VerticalLayout();
        verticallayout10.addClassNames(LumoUtility.Height.FULL, LumoUtility.Gap.XSMALL, LumoUtility.JustifyContent.CENTER, LumoUtility.AlignItems.END);
        verticallayout10.getElement().getThemeList().add("spacing");
        H2 a226 = new H2("226€");
        verticallayout10.add(a226);
        Span night2 = new Span("/ night");
        night2.addClassNames(LumoUtility.FontSize.SMALL);
        verticallayout10.add(night2);
        div10.add(verticallayout10);
        verticallayout4.add(div10);
        Div div16 = new Div();
        div16.getStyle().set("width", "908px").set("height", "1px");
        div16.addClassNames(LumoUtility.AlignSelf.STRETCH, LumoUtility.Background.CONTRAST_20, LumoUtility.BorderRadius.SMALL);
        verticallayout4.add(div16);
        Div div17 = new Div();
        div17.addClassNames(LumoUtility.AlignSelf.STRETCH);
        Div div18 = new Div();
        div18.getStyle().set("backgroundColor", "#d9d9d9").set("width", "160px").set("height", "146px");
        div18.addClassNames(LumoUtility.Height.FULL, LumoUtility.BorderRadius.SMALL);
        div17.add(div18);
        VerticalLayout verticallayout11 = new VerticalLayout();
        verticallayout11.addClassNames(LumoUtility.Flex.GROW, LumoUtility.Gap.MEDIUM, LumoUtility.Padding.MEDIUM);
        verticallayout11.getElement().getThemeList().add("spacing");
        VerticalLayout verticallayout12 = new VerticalLayout();
        verticallayout12.addClassNames(LumoUtility.AlignSelf.STRETCH, LumoUtility.Gap.SMALL);
        verticallayout12.getElement().getThemeList().add("spacing");
        HorizontalLayout horizontallayout20 = new HorizontalLayout();
        horizontallayout20.addClassNames(LumoUtility.Gap.MEDIUM, LumoUtility.AlignItems.CENTER);
        horizontallayout20.getElement().getThemeList().add("spacing");
        H3 opulentOasis = new H3("Opulent Oasis");
        horizontallayout20.add(opulentOasis);
        Span popular2 = new Span("Popular");
        popular2.getElement().getThemeList().add("badge pill");
        horizontallayout20.add(popular2);
        verticallayout12.add(horizontallayout20);
        HorizontalLayout horizontallayout21 = new HorizontalLayout();
        horizontallayout21.addClassNames(LumoUtility.AlignSelf.STRETCH, LumoUtility.Gap.LARGE, LumoUtility.AlignItems.CENTER);
        horizontallayout21.getElement().getThemeList().add("spacing");
        HorizontalLayout horizontallayout22 = new HorizontalLayout();
        horizontallayout22.addClassNames(LumoUtility.Gap.XSMALL, LumoUtility.AlignItems.CENTER);
        horizontallayout22.getElement().getThemeList().add("spacing");
        HorizontalLayout horizontallayout23 = new HorizontalLayout();
        horizontallayout23.setClassName("gap-x-s");
        Div div19 = new Div();
        div19.getStyle().set("backgroundColor", "#d9d9d9").set("width", "20px").set("height", "20px");
        div19.addClassNames(LumoUtility.BorderRadius.SMALL);
        horizontallayout23.add(div19);
        Div div20 = new Div();
        horizontallayout23.add(div20);
        horizontallayout22.add(horizontallayout23);
        Span kallioHelsinki = new Span("Kallio, Helsinki");
        kallioHelsinki.addClassNames(LumoUtility.FontSize.XSMALL);
        horizontallayout22.add(kallioHelsinki);
        horizontallayout21.add(horizontallayout22);
        HorizontalLayout horizontallayout24 = new HorizontalLayout();
        horizontallayout24.addClassNames(LumoUtility.Gap.SMALL, LumoUtility.AlignItems.CENTER);
        horizontallayout24.getElement().getThemeList().add("spacing");
        HorizontalLayout horizontallayout25 = new HorizontalLayout();
        horizontallayout25.setClassName("gap-x-m");
        Div div21 = new Div();
        div21.getStyle().set("backgroundColor", "#d9d9d9").set("width", "20px").set("height", "20px");
        div21.addClassNames(LumoUtility.BorderRadius.SMALL);
        horizontallayout25.add(div21);
        Div div22 = new Div();
        horizontallayout25.add(div22);
        horizontallayout24.add(horizontallayout25);
        Span a91 = new Span("9.1");
        a91.addClassNames(LumoUtility.FontSize.XSMALL);
        horizontallayout24.add(a91);
        horizontallayout21.add(horizontallayout24);
        verticallayout12.add(horizontallayout21);
        verticallayout11.add(verticallayout12);
        HorizontalLayout horizontallayout26 = new HorizontalLayout();
        horizontallayout26.addClassNames(LumoUtility.AlignSelf.STRETCH, LumoUtility.Gap.SMALL, LumoUtility.AlignItems.CENTER);
        horizontallayout26.getElement().getThemeList().add("spacing");
        Span KingBed1QueenBed2 = new Span("1 king bed, 1 queen bed");
        horizontallayout26.add(KingBed1QueenBed2);
        Span a7 = new Span("-");
        a7.setClassName("text-xxs");
        horizontallayout26.add(a7);
        Span M3 = new Span("30 m²");
        horizontallayout26.add(M3);
        Span a8 = new Span("-");
        a8.setClassName("text-xxs");
        horizontallayout26.add(a8);
        Span Adults1Child2 = new Span("2 adults, 1 child");
        horizontallayout26.add(Adults1Child2);
        verticallayout11.add(horizontallayout26);
        div17.add(verticallayout11);
        VerticalLayout verticallayout13 = new VerticalLayout();
        verticallayout13.addClassNames(LumoUtility.Height.FULL, LumoUtility.Gap.XSMALL, LumoUtility.JustifyContent.CENTER, LumoUtility.AlignItems.END);
        verticallayout13.getElement().getThemeList().add("spacing");
        H2 a210 = new H2("210€");
        verticallayout13.add(a210);
        Span night3 = new Span("/ night");
        night3.addClassNames(LumoUtility.FontSize.SMALL);
        verticallayout13.add(night3);
        div17.add(verticallayout13);
        verticallayout4.add(div17);
        Div div23 = new Div();
        div23.getStyle().set("width", "908px").set("height", "1px");
        div23.addClassNames(LumoUtility.AlignSelf.STRETCH, LumoUtility.Background.CONTRAST_20, LumoUtility.BorderRadius.SMALL);
        verticallayout4.add(div23);
        Div div24 = new Div();
        div24.addClassNames(LumoUtility.AlignSelf.STRETCH);
        Div div25 = new Div();
        div25.getStyle().set("backgroundColor", "#d9d9d9").set("width", "160px").set("height", "146px");
        div25.addClassNames(LumoUtility.Height.FULL, LumoUtility.BorderRadius.SMALL);
        div24.add(div25);
        VerticalLayout verticallayout14 = new VerticalLayout();
        verticallayout14.addClassNames(LumoUtility.Flex.GROW, LumoUtility.Gap.MEDIUM, LumoUtility.Padding.MEDIUM);
        verticallayout14.getElement().getThemeList().add("spacing");
        VerticalLayout verticallayout15 = new VerticalLayout();
        verticallayout15.addClassNames(LumoUtility.AlignSelf.STRETCH, LumoUtility.Gap.SMALL);
        verticallayout15.getElement().getThemeList().add("spacing");
        HorizontalLayout horizontallayout27 = new HorizontalLayout();
        horizontallayout27.addClassNames(LumoUtility.Gap.MEDIUM, LumoUtility.AlignItems.CENTER);
        horizontallayout27.getElement().getThemeList().add("spacing");
        H3 cityInn = new H3("City Inn");
        horizontallayout27.add(cityInn);
        Span trendy = new Span("Trendy");
        trendy.getElement().getThemeList().add("badge pill");
        horizontallayout27.add(trendy);
        verticallayout15.add(horizontallayout27);
        HorizontalLayout horizontallayout28 = new HorizontalLayout();
        horizontallayout28.addClassNames(LumoUtility.AlignSelf.STRETCH, LumoUtility.Gap.LARGE, LumoUtility.AlignItems.CENTER);
        horizontallayout28.getElement().getThemeList().add("spacing");
        HorizontalLayout horizontallayout29 = new HorizontalLayout();
        horizontallayout29.addClassNames(LumoUtility.Gap.XSMALL, LumoUtility.AlignItems.CENTER);
        horizontallayout29.getElement().getThemeList().add("spacing");
        HorizontalLayout horizontallayout30 = new HorizontalLayout();
        horizontallayout30.setClassName("gap-x-s");
        Div div26 = new Div();
        div26.getStyle().set("backgroundColor", "#d9d9d9").set("width", "20px").set("height", "20px");
        div26.addClassNames(LumoUtility.BorderRadius.SMALL);
        horizontallayout30.add(div26);
        Div div27 = new Div();
        horizontallayout30.add(div27);
        horizontallayout29.add(horizontallayout30);
        Span kamppiHelsinki2 = new Span("Kamppi, Helsinki");
        kamppiHelsinki2.addClassNames(LumoUtility.FontSize.XSMALL);
        horizontallayout29.add(kamppiHelsinki2);
        horizontallayout28.add(horizontallayout29);
        HorizontalLayout horizontallayout31 = new HorizontalLayout();
        horizontallayout31.addClassNames(LumoUtility.Gap.SMALL, LumoUtility.AlignItems.CENTER);
        horizontallayout31.getElement().getThemeList().add("spacing");
        HorizontalLayout horizontallayout32 = new HorizontalLayout();
        horizontallayout32.setClassName("gap-x-m");
        Div div28 = new Div();
        div28.getStyle().set("backgroundColor", "#d9d9d9").set("width", "20px").set("height", "20px");
        div28.addClassNames(LumoUtility.BorderRadius.SMALL);
        horizontallayout32.add(div28);
        Div div29 = new Div();
        horizontallayout32.add(div29);
        horizontallayout31.add(horizontallayout32);
        Span a78 = new Span("7.8");
        a78.addClassNames(LumoUtility.FontSize.XSMALL);
        horizontallayout31.add(a78);
        horizontallayout28.add(horizontallayout31);
        verticallayout15.add(horizontallayout28);
        verticallayout14.add(verticallayout15);
        HorizontalLayout horizontallayout33 = new HorizontalLayout();
        horizontallayout33.addClassNames(LumoUtility.AlignSelf.STRETCH, LumoUtility.Gap.SMALL, LumoUtility.AlignItems.CENTER);
        horizontallayout33.getElement().getThemeList().add("spacing");
        Span KingBed1SofaBed = new Span("1 king bed, 1 sofa bed");
        horizontallayout33.add(KingBed1SofaBed);
        Span a9 = new Span("-");
        a9.setClassName("text-xxs");
        horizontallayout33.add(a9);
        Span M4 = new Span("25 m²");
        horizontallayout33.add(M4);
        Span a10 = new Span("-");
        a10.setClassName("text-xxs");
        horizontallayout33.add(a10);
        Span Adults2Children = new Span("2 adults, 2 children");
        horizontallayout33.add(Adults2Children);
        verticallayout14.add(horizontallayout33);
        div24.add(verticallayout14);
        VerticalLayout verticallayout16 = new VerticalLayout();
        verticallayout16.addClassNames(LumoUtility.Height.FULL, LumoUtility.Gap.XSMALL, LumoUtility.JustifyContent.CENTER, LumoUtility.AlignItems.END);
        verticallayout16.getElement().getThemeList().add("spacing");
        H2 a179 = new H2("179€");
        verticallayout16.add(a179);
        Span night4 = new Span("/ night");
        night4.addClassNames(LumoUtility.FontSize.SMALL);
        verticallayout16.add(night4);
        div24.add(verticallayout16);
        verticallayout4.add(div24);
        verticallayout3.add(verticallayout4);
        verticallayout.add(verticallayout3);
        add(verticallayout);
    }
}
