create table public.task
(
    task_id       bigint generated by default as identity
        primary key,
    creation_date timestamp(6) with time zone not null,
    description   varchar(255)                not null,
    due_date      date
);
